### ISSUE TITLE
RubyML list

### ISSUE THREAD

**Issue by arbox** [asafschers/scoruby#1]
Dear Asaf,

I've recently added your project to our RubyML list: https://github.com/arbox/machine-learning-with-ruby

I wonder if you want to participate in the Ruby for ML network. You could do this in a very simple step by adding the `rubyml` topic to your GitHub repository. You may want to spread a word on Twitter or on other media :)

Thank you for the project!

**Comment by asafschers** [comment]
Sure, what do you mean by "adding the rubyml topic to your GitHub repository" ?
Thanks :)

**Comment by arbox** [comment]
GitHub recently introduced "topics", user defined (or system proposed) tag for every repository. They appear under the repo description. RubyML is a standard topic (tag) for every project related to ML and Ruby.

**Comment by asafschers** [comment]
Of course, added now.
