### ISSUE TITLE
Small wiki update

### ISSUE THREAD

**Issue by ankane** [asafschers/scoruby#14]
Hey, noticed a small issue (possibly just outdated) with the random forest wiki. The example uses:

```ruby
random_forest.predict(features)

=> "0"
```

I think this should be:

```ruby
random_forest.score(features)

=> {:label=>"0", :score=>0.882}
```

**Comment by asafschers** [comment]
Fixed now, thanks again :)

**Comment by ankane** [comment]
Awesome 👍
