### ISSUE TITLE
Namespace the files under lib directory

### ISSUE THREAD

**Issue by pts-owentran** [asafschers/scoruby#3]
The classes in scoruby are not namespaced under Scoruby package and interferes with generic named things in a rails5 project (especially the Features module under test). 

Can you move all the top level files under scoruby:

* decision.rb
* features.rb
* models_factory.rb
* node.rb
* predicate_factory.rb

**Comment by pts-owentran** [comment]
Submitted PR #4

**Comment by asafschers** [comment]
Thanks! 
Planned on doing this for a while :)

**Comment by asafschers** [comment]
Deployed 0.2.3 with namespacing.
