### ISSUE TITLE
Support for sklearn2pmml generated PMML

### ISSUE THREAD

**Issue by annebyrne** [asafschers/scoruby#9]
Scoruby does not seem to tolerate the XML generated via sklearn2pmml. So far it's broken at the following steps:

1. modelName check in `model_factory`
2. `@score = xml.attribute('score').to_s` when calling `.score(features)`

**Comment by asafschers** [comment]
Hey

1. I can't reproduce the issue - the model is loaded when I run  - 
```ruby
Scoruby.load_model('spec/fixtures/sklearn_format.txt')
```

2. I think the model isn't loaded correctly because of the 10th TreeModel element (in <Segment id="10">) in your PMML file  is missing a space between the attributes algorithmName and missingValueStrategy, when I added the space the .score error stopped and the model scored - I should add an indicative error message.

Please tell me if it works
Thanks!

**Comment by vruusmann** [comment]
> your PMML file is missing a space between the attributes algorithmName and missingValueStrategy

@annebyrne - Can you confirm that you have not edited this PMML file manually? That is, you have no idea how this space character went missing?

**Comment by annebyrne** [comment]
Apologies - I had uploaded by accident the version I edited to test for the discrepancies in the XML. I've updated description to select the unedited version.

**Comment by harrysalmon** [comment]
Thank you for looking into this @vruusmann and @asafschers. I've generated example PMML and included the python script to reproduce. 

[example_sklearn_rf.pmml.txt](https://github.com/asafschers/scoruby/files/1730840/example_sklearn_rf.pmml.txt)
[example_sklearn_rf.py.txt](https://github.com/asafschers/scoruby/files/1730841/example_sklearn_rf.py.txt)

**Comment by asafschers** [comment]
Modified model_factory to identify random forest models by random forest text in extension element and released 0.3.2, should solve the issue for now.
@annebyrne @harrysalmon - Are there any other issues? scoring seems to work for me
@vruusmann - seems like miningModel element should have modelName="randomForest_Model" like the R version, what do you think?

**Comment by annebyrne** [comment]
Brill, thanks for the quick movement on this @asafschers. Will update issue shortly on whether this resolves our issue.

**Comment by harrysalmon** [comment]
Thank you @asafschers

**Comment by vruusmann** [comment]
@asafschers The `MiningModel@modelName` attribute is optional free-form text. It is not suitable for identifying the actual scoring algorithm (eg. RF vs. GBT) - please consider using the `MiningModel/Segmentation@multipleModelMethod` attribute for that (will be `(weighted)average` for RF-family of algorithms, and `(weighted)sum` for GBT-family of algorithms).

**Comment by asafschers** [comment]
Great, I'll consider multipleModelMethod.
Thanks!

**Comment by annebyrne** [comment]
This has fixed issue, and score works fine now. Thanks for your swift help @asafschers !
